
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkamesozxdakvvxldiza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rYW1lc296eGRha3Z2eGxkaXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTU3NDUsImV4cCI6MjA2Mjk5MTc0NX0.7laPUBC4XIQzgGhbRo35jS-b2TpNn9xEsPLRgEWKtjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined
  }
});
